# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    

    - name: Create fake artifact
      run: |
        mkdir -p artifact
        echo hello > artifact/world.txt
        
    - name: Tag Release
      run: echo RELEASE_VERSION="v$(date +'%Y.%m.%d')" >> $GITHUB_ENV          
    
    - name: Release Version
      run: echo $RELEASE_VERSION

    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ format('{0}', env.RELEASE_VERSION) }}
        files: artifact/world.txt
    
